using System.IO;
using NUnit.Framework;
using reromanlee.Wireframes.Editor;
using UnityEditor;
using UnityEngine;

namespace reromanlee.Wireframes.Tests
{
    /// <summary>The symbol enums generated for glyph packs.</summary>
    public class GlyphEnumGeneratorTests
    {
        private const string Folder = "Assets/WireframesGlyphEnumTest";
        private const string DefaultSymbolsPath = "Packages/com.reromanlee.wireframes/Runtime/Glyphs/Default/Default Symbols.asset";

        private WireframeGlyphPack _pack;

        [SetUp]
        public void CreatePack()
        {
            _pack = ScriptableObject.CreateInstance<WireframeGlyphPack>();
            _pack.name = "Test Pack";
            GlyphStroke line = new(new[] { Vector2.zero, Vector2.one }, false);
            _pack.SetGlyphs(null, new[] { new SymbolGlyph("ArrowUp", new[] { line }), new SymbolGlyph("Heart", null) });
        }

        [TearDown]
        public void DestroyPack()
        {
            if (AssetDatabase.Contains(_pack))
            {
                File.Delete(FileUtil.GetPhysicalPath($"{Folder}/TestPack.cs"));
                AssetDatabase.DeleteAsset(Folder);
            }
            else
            {
                Object.DestroyImmediate(_pack);
            }
        }

        [Test]
        public void Enum_HasNoneAndAMemberPerSymbolValuedByItsKey()
        {
            _pack.EnumSettings = new GlyphEnumSettings("TestSymbols", "Game.Icons", null);

            string source = GlyphEnumGenerator.Generate(_pack);

            Assert.That(source, Is.EqualTo(
                "// <auto-generated>\n"
                + "// Generated by Wireframes from the glyph pack Test Pack. Edit its symbols in the Glyph Editor and\n"
                + "// generate the enum again instead of editing this file.\n"
                + "// Glyph pack GUID: \n"
                + "// </auto-generated>\n"
                + "\n"
                + "namespace Game.Icons\n"
                + "{\n"
                + "    /// <summary>The symbols of the glyph pack Test Pack, for symbol shapes and components.</summary>\n"
                + "    public enum TestSymbols\n"
                + "    {\n"
                + "        None = 0,\n"
                + "        ArrowUp = 154847355,\n"
                + "        Heart = -1226833789\n"
                + "    }\n"
                + "}\n"));
        }

        [Test]
        public void EnumWithoutANamespace_IsLeftInTheGlobalOne()
        {
            _pack.EnumSettings = new GlyphEnumSettings("TestSymbols", null, null);
            string rootNamespace = EditorSettings.projectGenerationRootNamespace;
            EditorSettings.projectGenerationRootNamespace = string.Empty;
            try
            {
                string source = GlyphEnumGenerator.Generate(_pack);

                Assert.That(source, Does.Not.Contain("namespace"));
                Assert.That(source, Does.Contain("\npublic enum TestSymbols\n{\n    None = 0,\n"));
            }
            finally
            {
                EditorSettings.projectGenerationRootNamespace = rootNamespace;
            }
        }

        [TestCase("Default Symbols", "DefaultSymbols")]
        [TestCase("my-symbols 2", "MySymbols2")]
        [TestCase("2D icons", "_2DIcons")]
        [TestCase("!!!", "Symbols")]
        public void PackNames_BecomeEnumNames(string packName, string enumName)
        {
            Assert.That(GlyphEnumGenerator.IdentifierOf(packName), Is.EqualTo(enumName));
        }

        [Test]
        public void Problems_AreFoundBeforeAnythingIsWritten()
        {
            Assert.That(GlyphEnumGenerator.FindProblem(_pack), Is.Null);

            _pack.SetGlyphs(null, new[] { new SymbolGlyph("Heart", null), new SymbolGlyph("Heart", null) });
            Assert.That(GlyphEnumGenerator.FindProblem(_pack), Does.Contain("two symbols named Heart"));

            _pack.SetGlyphs(null, new[] { new SymbolGlyph("class", null) });
            Assert.That(GlyphEnumGenerator.FindProblem(_pack), Does.Contain("C# keyword"));

            _pack.SetGlyphs(null, null);
            _pack.EnumSettings = new GlyphEnumSettings("Two Words", null, null);
            Assert.That(GlyphEnumGenerator.FindProblem(_pack), Does.Contain("can't name an enum"));

            _pack.EnumSettings = new GlyphEnumSettings("Icons", "Game..Icons", null);
            Assert.That(GlyphEnumGenerator.FindProblem(_pack), Does.Contain("isn't a namespace"));
        }

        [Test]
        public void EnumScript_IsNextToThePackAndOutOfDateUntilWrittenAsGenerated()
        {
            AssetDatabase.CreateFolder("Assets", Path.GetFileName(Folder));
            AssetDatabase.CreateAsset(_pack, $"{Folder}/Test Pack.asset");
            string scriptPath = GlyphEnumGenerator.ScriptPathOf(_pack);
            Assert.That(scriptPath, Is.EqualTo($"{Folder}/TestPack.cs"));
            Assert.That(GlyphEnumGenerator.IsOutOfDate(_pack), Is.True);

            // Written without importing it, so no scripts compile during the test.
            File.WriteAllText(FileUtil.GetPhysicalPath(scriptPath), GlyphEnumGenerator.Generate(_pack).Replace("\n", "\r\n"));
            Assert.That(GlyphEnumGenerator.Generate(_pack), Does.Contain(AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(_pack))));
            Assert.That(GlyphEnumGenerator.IsOutOfDate(_pack), Is.False);

            _pack.SetGlyphs(null, new[] { new SymbolGlyph("Star", null) });
            Assert.That(GlyphEnumGenerator.IsOutOfDate(_pack), Is.True);
        }

        [Test]
        public void DefaultSymbolsEnum_MatchesItsPack()
        {
            WireframeGlyphPack pack = AssetDatabase.LoadAssetAtPath<WireframeGlyphPack>(DefaultSymbolsPath);

            Assert.That(GlyphEnumGenerator.ScriptPathOf(pack), Does.EndWith("/Default/DefaultSymbols.cs"));
            Assert.That(GlyphEnumGenerator.IsOutOfDate(pack), Is.False, "Generate the Default Symbols enum again.");
        }
    }
}
