using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace reromanlee.Wireframes.Editor
{
    /// <summary>
    /// Writes a glyph pack's symbol enum: a C# file next to the pack with one member per symbol, valued by its keyword's
    /// hash, plus None. The file names the pack's GUID, so it's found again wherever it's moved, and a copy of the pack
    /// never overwrites the original's enum.
    /// </summary>
    internal static class GlyphEnumGenerator
    {
        private const string Indent = "    ";
        private static readonly Regex PackGuidLine = new(@"^// Glyph pack GUID: ([0-9a-f]{32})", RegexOptions.Multiline);

        /// <summary>The enum's name: the pack's setting, or the pack's name made into a C# identifier.</summary>
        internal static string EnumNameOf(WireframeGlyphPack pack)
        {
            string name = pack.EnumSettings.Name;
            return name.Length > 0 ? name : IdentifierOf(pack.name);
        }

        /// <summary>The enum's namespace: the pack's setting, or the project's root namespace; empty for none.</summary>
        internal static string NamespaceOf(WireframeGlyphPack pack)
        {
            string namespaceName = pack.EnumSettings.Namespace;
            return namespaceName.Length > 0 ? namespaceName : EditorSettings.projectGenerationRootNamespace ?? string.Empty;
        }

        /// <summary>
        /// Returns why the pack's enum can't be generated, or null when it can: a keyword that isn't valid, a keyword
        /// used twice, two keywords with the same hash, or a name or namespace that isn't a C# identifier.
        /// </summary>
        internal static string FindProblem(WireframeGlyphPack pack)
        {
            string enumName = EnumNameOf(pack);
            if (!IsIdentifier(enumName))
            {
                return $"'{enumName}' can't name an enum. Set a C# identifier as the enum's name in Pack Settings.";
            }
            string namespaceName = NamespaceOf(pack);
            if (namespaceName.Length > 0 && !Array.TrueForAll(namespaceName.Split('.'), IsIdentifier))
            {
                return $"'{namespaceName}' isn't a namespace. Set C# identifiers joined by dots in Pack Settings.";
            }
            Dictionary<int, string> keywords = new();
            foreach (SymbolGlyph symbol in pack.Symbols)
            {
                string keyword = symbol.Keyword;
                string problem = SymbolKeys.FindProblem(keyword);
                if (problem != null)
                {
                    return keyword.Length > 0 ? $"{keyword}: {problem}" : problem;
                }
                int key = SymbolKeys.Of(keyword);
                if (keywords.TryGetValue(key, out string other))
                {
                    return other == keyword
                        ? $"The pack has two symbols named {keyword}."
                        : $"{other} and {keyword} have the same hash, so one of them needs another name.";
                }
                keywords.Add(key, keyword);
            }
            return null;
        }

        /// <summary>The source of the pack's enum, with \n line endings.</summary>
        internal static string Generate(WireframeGlyphPack pack)
        {
            string enumName = EnumNameOf(pack);
            string namespaceName = NamespaceOf(pack);
            string guid = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(pack));
            string indent = namespaceName.Length > 0 ? Indent : string.Empty;

            StringBuilder source = new();
            source.Append("// <auto-generated>\n");
            source.Append($"// Generated by Wireframes from the glyph pack {pack.name}. Edit its symbols in the Glyph Editor and\n");
            source.Append("// generate the enum again instead of editing this file.\n");
            source.Append($"// Glyph pack GUID: {guid}\n");
            source.Append("// </auto-generated>\n\n");
            if (namespaceName.Length > 0)
            {
                source.Append($"namespace {namespaceName}\n{{\n");
            }
            string summaryName = pack.name.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
            source.Append($"{indent}/// <summary>The symbols of the glyph pack {summaryName}, for symbol shapes and components.</summary>\n");
            source.Append($"{indent}public enum {enumName}\n{indent}{{\n");
            source.Append($"{indent}{Indent}{SymbolKeys.NoneName} = {SymbolKeys.None}");
            foreach (SymbolGlyph symbol in pack.Symbols)
            {
                source.Append($",\n{indent}{Indent}{symbol.Keyword} = {SymbolKeys.Of(symbol.Keyword)}");
            }
            source.Append($"\n{indent}}}\n");
            if (namespaceName.Length > 0)
            {
                source.Append("}\n");
            }
            return source.ToString();
        }

        /// <summary>
        /// Where the pack's enum is: the script it was last written to, found by GUID, while that script still names the
        /// pack, or otherwise a script named after the enum next to the pack. Empty for a pack that isn't an asset.
        /// </summary>
        internal static string ScriptPathOf(WireframeGlyphPack pack)
        {
            string packPath = AssetDatabase.GetAssetPath(pack);
            if (string.IsNullOrEmpty(packPath))
            {
                return string.Empty;
            }
            string scriptGuid = pack.EnumSettings.ScriptGuid;
            if (scriptGuid.Length > 0)
            {
                string scriptPath = AssetDatabase.GUIDToAssetPath(scriptGuid);
                if (!string.IsNullOrEmpty(scriptPath) && IsScriptOf(scriptPath, packPath))
                {
                    return scriptPath;
                }
            }
            return $"{Path.GetDirectoryName(packPath)?.Replace('\\', '/')}/{EnumNameOf(pack)}.cs";
        }

        /// <summary>
        /// True when the pack is an asset whose enum script is missing or differs from what generating it now would write.
        /// </summary>
        internal static bool IsOutOfDate(WireframeGlyphPack pack)
        {
            string scriptPath = ScriptPathOf(pack);
            if (scriptPath.Length == 0)
            {
                return false;
            }
            string path = FileUtil.GetPhysicalPath(scriptPath);
            if (!File.Exists(path))
            {
                return true;
            }
            string written = File.ReadAllText(path).Replace("\r\n", "\n");
            return written != Generate(pack);
        }

        /// <summary>
        /// Writes the pack's enum and imports it, which compiles scripts again, and remembers the script on the pack.
        /// </summary>
        /// <exception cref="InvalidOperationException">The enum can't be generated, as <see cref="FindProblem"/> tells.</exception>
        internal static void Write(WireframeGlyphPack pack)
        {
            if (!AssetDatabase.Contains(pack))
            {
                throw new InvalidOperationException("Save the glyph pack as an asset before generating its enum.");
            }
            string problem = FindProblem(pack);
            if (problem != null)
            {
                throw new InvalidOperationException(problem);
            }
            string scriptPath = ScriptPathOf(pack);
            string physicalPath = FileUtil.GetPhysicalPath(scriptPath);
            if (File.Exists(physicalPath) && !IsScriptOf(scriptPath, AssetDatabase.GetAssetPath(pack)))
            {
                throw new InvalidOperationException(
                    $"{scriptPath} already exists and wasn't generated for this pack. Set another enum name in Pack Settings.");
            }
            File.WriteAllText(physicalPath, Generate(pack), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(scriptPath);

            SerializedObject serialized = new(pack);
            SerializedProperty settings = serialized.FindProperty(WireframeGlyphPack.EnumSettingsField);
            settings.FindPropertyRelative(GlyphEnumSettings.ScriptGuidField).stringValue =
                AssetDatabase.AssetPathToGUID(scriptPath);
            serialized.ApplyModifiedPropertiesWithoutUndo();
            AssetDatabase.SaveAssetIfDirty(pack);
        }

        /// <summary>
        /// A C# identifier made from <paramref name="name"/>: its letters and digits, each word starting with a capital,
        /// and an underscore first when it would start with a digit.
        /// </summary>
        internal static string IdentifierOf(string name)
        {
            StringBuilder identifier = new();
            bool startsWord = true;
            foreach (char character in name)
            {
                bool isLetter = character is >= 'A' and <= 'Z' or >= 'a' and <= 'z';
                bool isDigit = character is >= '0' and <= '9';
                if (!isLetter && !isDigit)
                {
                    startsWord = true;
                    continue;
                }
                identifier.Append(startsWord ? char.ToUpperInvariant(character) : character);
                startsWord = false;
            }
            if (identifier.Length == 0)
            {
                return "Symbols";
            }
            if (identifier[0] is >= '0' and <= '9')
            {
                identifier.Insert(0, '_');
            }
            return identifier.ToString();
        }

        private static bool IsIdentifier(string name)
        {
            return SymbolKeys.FindProblem(name) == null || name == SymbolKeys.NoneName;
        }

        private static bool IsScriptOf(string scriptPath, string packPath)
        {
            string physicalPath = FileUtil.GetPhysicalPath(scriptPath);
            if (!File.Exists(physicalPath))
            {
                return false;
            }
            Match match = PackGuidLine.Match(File.ReadAllText(physicalPath));
            return match.Success && match.Groups[1].Value == AssetDatabase.AssetPathToGUID(packPath);
        }
    }
}
