// <auto-generated>
// Generated by Wireframes from the glyph pack Default Symbols. Edit its symbols in the Glyph Editor and
// generate the enum again instead of editing this file.
// Glyph pack GUID: d930073e5928747418094a1518c82e8f
// </auto-generated>

namespace reromanlee.Wireframes
{
    /// <summary>The symbols of the glyph pack Default Symbols, for symbol shapes and components.</summary>
    public enum DefaultSymbols
    {
        None = 0,
        ArrowUp = 154847355,
        ArrowDown = -1800131538,
        ArrowLeft = -1095283229,
        ArrowRight = 1371226220,
        Check = 1496092135,
        Cross = -1234971333,
        Plus = 730684821,
        Minus = -906706865,
        Warning = 935656591,
        Info = -1881020891,
        Question = 10944613,
        Heart = -1226833789,
        Star = 1365736337,
        Circle = -2128132439,
        Square = -87454618,
        Triangle = -444037467,
        Diamond = -547800249,
        Crosshair = 1240723459,
        Flag = 1041691895,
        Play = 699101059,
        Pause = 1157218093,
        Stop = 1266644741,
        Bolt = 896955494
    }
}
